---
- hosts: localhost
  roles:
    - role: elnappoo.apt-cacher-ng

- hosts: all
  tasks:
    - name: Set up apt proxy
      template: src=templates/apt_proxy.conf dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644
      when: ansible_os_family == "Debian" and apt_proxy is defined
      vars:
        apt_proxy: "192.168.1.100:3142"

- hosts: localhost
  roles:
    - name: "Google Cloud Print"
      role: JonTheNiceGuy.google-cloud-print
      gcp_config_file_src: files/gcp.json
    - name: "NTP"
      role: geerlingguy.ntp
      ntp_timezone: Europe/London
      ntp_manage_config: true
      ntp_restrict: ["10.0.0.0/8", "127.0.0.1", "172.16.0.0/12", "192.168.0.0/16"]
      ntp_servers: ["127.0.0.1 iburst", "0.ubuntu.pool.ntp.org iburst", "1.ubuntu.pool.ntp.org iburst", "2.ubuntu.pool.ntp.org iburst", "3.ubuntu.pool.ntp.org iburst"]
#    - name: "Cups"
#      role: HP41.cups
#      cups_admin_grp: sudo
#      cups_printer_list:
#        - name: HPPrinter
#          uri: "hp:/net/Officejet_6500_E709n?ip=192.168.1.55"
#          default_printer: true
#          driver: "drv:///hpcups.drv/hp-officejet_6500_e709n.ppd HP Officejet 6500 e709n, hpcups 3.16.3"
#          location: "Playroom"
#          info: "HP Officejet 6500 e709n"
#          shared: true

- hosts: all:!localhost
  roles:
    - name: NTP
      role: geerlingguy.ntp
      ntp_timezone: Europe/London
      ntp_manage_config: true
      ntp_servers: ["127.0.0.1","192.168.1.100"]
