---
- name: "Set up Proxy for apt"
  hosts: localhost
  roles:
  - role: elnappoo.apt-cacher-ng

- name: "Configure Proxy for apt"
  hosts: all
  tasks:
  - name: Set up apt proxy
    template: src=templates/apt_proxy.conf dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644
    when: ansible_os_family == "Debian" and apt_proxy is defined
    vars:
      apt_proxy: "{{ hostvars[localhost].ansible_default_ipv4.address }}:3142"

- name: "Setup NTP Server"
  hosts: localhost
  roles:
  - name: "NTP"
    role: geerlingguy.ntp
    ntp_timezone: Europe/London
    ntp_manage_config: true
    ntp_restrict: ["10.0.0.0/8", "127.0.0.1", "172.16.0.0/12", "192.168.0.0/16"]
    ntp_servers: ["127.0.0.1 iburst", "0.ubuntu.pool.ntp.org iburst", "1.ubuntu.pool.ntp.org iburst", "2.ubuntu.pool.ntp.org iburst", "3.ubuntu.pool.ntp.org iburst"]

- name: "Setup NTP Clients"
  hosts: all:!localhost
  roles:
    - name: NTP
      role: geerlingguy.ntp
      ntp_timezone: Europe/London
      ntp_manage_config: true
      ntp_servers: ["127.0.0.1","{{ hostvars[localhost].ansible_default_ipv4.address }}"]

- name: "Install Docker-ce"
  hosts: localhost
  tasks:
  - apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - apt:
      name: docker-ce
      update_cache: yes
      state: present

- name: "Setup NFS Server"
  hosts: localhost
  roles:
  - name: "NFS"
    role: geerlingguy.nfs
    nfs_exports: { "/content *(rw,sync,no_root_squash)" }

- name: "Setup NFS mount"
  hosts: ContentSources
  tasks:
  - name: Install nfs-common
    apt:
      name: nfs-common
      state: present
  - name: Ensure content path is there
    file:
      path: /content
      state: directory
      mode: 0777
  - name: Mount NFS
    mount:
      path: /content
      src: "{{ hostvars[localhost].ansible_default_ipv4.address }}:/content"
      fstype: nfs
      opts: rsize=8192,wsize=8192,timeo=14,intr
      state: mounted
