---
- hosts: localhost
  roles:
    - { role: elnappoo.apt-cacher-ng }

- hosts: all
  tasks:
    - name: Set up apt proxy
      template: src=templates/apt_proxy.conf dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644
      when: ansible_os_family == "Debian" and apt_proxy is defined
      vars:
        apt_proxy: "192.168.1.100:3142"

- hosts: localhost
  roles:
    - { role: geerlingguy.ntp, ntp_timezone: Europe/London, ntp_manage_config: true, ntp_restrict: ["10.0.0.0/8", "127.0.0.1", "172.16.0.0/12", "192.168.0.0/16"], ntp_servers: ["127.0.0.1 iburst", "0.ubuntu.pool.ntp.org iburst", "1.ubuntu.pool.ntp.org iburst", "2.ubuntu.pool.ntp.org iburst", "3.ubuntu.pool.ntp.org iburst"] }

- hosts: all:!localhost
  roles:
    - { role: geerlingguy.ntp, ntp_timezone: Europe/London, ntp_manage_config: true, ntp_servers: ["127.0.0.1","192.168.1.100"] }
